[package]
name = "starbot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
rayon = "1.5"
actix = "0.12"
actix-rt = "2.5"
noise = "0.7"
pathfinding = "3.0"