[package]
name = "starbot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
tracing = "0.1.40"
tracing-appender = "0.2"
tracing-subscriber = "0.3.18"